stages:
  prepare:
    cmd: python src/scripts/celeba/prepare_celeba.py
    deps:
    - src/scripts/celeba/prepare_celeba.py
    outs:
    - data/celeba/img_align_celeba
  train:
    cmd: python src/scripts/celeba/train.py
    deps:
    - src/scripts/celeba/train.py
